import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.scss";
import DonationDisplayCard from "../components/DonationDisplayCard/DonationDisplayCard";
import StrokedTitle from "../components/StrokedTitle/StrokedTitle";
import BlogDisplayCard from "../components/BlogDisplayCard/BlogDisplayCard";
import EventDisplayCard from "../components/EventDisplayCard/EventDisplayCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
      <DonationDisplayCard />
      <section className={styles.section}>
        <StrokedTitle title="Read Our News" />
        <div className={styles.sectionNews}>
          <BlogDisplayCard
            imagePath="https://assets.website-files.com/61a3ad3365af7a7bfde3e595/61a3ad3365af7a77bbe3e59a_blog-main-1.jpg"
            title="Don't destroy greenery and don't spoil scenery"
            description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim"
          />
          <BlogDisplayCard
            imagePath="https://assets.website-files.com/61a3ad3365af7a7bfde3e595/61a3ad3365af7a0eaae3e59f_blog-main-2.jpg"
            title="Is climate change happening faster than expected?"
            description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim"
          />
          <BlogDisplayCard
            imagePath="https://assets.website-files.com/61a3ad3365af7a7bfde3e595/61a3ad3365af7a12f7e3e5a1_blog-main-3.jpg"
            title="Top 10 facts about wind farms you didn't know"
            description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim"
          />
          <BlogDisplayCard
            imagePath="https://assets.website-files.com/61a3ad3365af7a7bfde3e595/61a3ad3365af7a2bb6e3e5a3_blog-main-4.jpg"
            title="Our goal is to make water available for everyone"
            description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim"
          />
        </div>
      </section>
      <section className={styles.section}>
        <StrokedTitle title="Events" />
        <div className={styles.sectionEvents}>
          <EventDisplayCard title="Say no to plastic usage and save the planet" />
          <EventDisplayCard title="Weekly cleaning program" />
        </div>
      </section>
    </>
  );
}
